// Ten interfaces modeled as edges so we can traverse the dependency graph.
const now = new Date();
const hoursAgo = (h) => new Date(now.getTime() - h * 3600 * 1000);

export const interfaces = [
  {
    key: "if-hospital-850",
    name: "Hospital Order 850",
    description: "Inbound EDI 850 purchase order from Hospital 123.",
    type: "EDI",
    protocol: "X12",
    message_type: "850",
    source: "hospital-123",
    target: "edi-gateway",
    middleware: [],
    data_entities: ["purchase-order", "inventory-request"],
    owners: ["b2b-operations"],
    downstream_systems: ["edi-gateway"],
    downstream_interfaces: ["if-gateway-x12"],
    lifecycle: "production",
    version: "2.3",
    sla: "Process within 5 minutes",
    last_status: "healthy",
    last_success_at: hoursAgo(1),
    business_impact: "Hospital supply orders cannot be placed.",
  },
  {
    key: "if-gateway-x12",
    name: "Gateway to X12 Translation",
    description: "EDI Gateway hands raw X12 envelopes to the X12 Translator.",
    type: "EDI",
    protocol: "X12",
    message_type: "850",
    source: "edi-gateway",
    target: "x12-translator",
    owners: ["b2b-operations"],
    downstream_systems: ["x12-translator"],
    downstream_interfaces: ["if-x12-integration"],
    lifecycle: "production",
    version: "2.3",
    sla: "Translate within 2 minutes",
    last_status: "healthy",
    last_success_at: hoursAgo(1),
    business_impact: "Orders stuck untranslated in the gateway.",
  },
  {
    key: "if-x12-integration",
    name: "X12 to Integration API",
    description: "Translated canonical order routed to the Integration API.",
    type: "REST",
    protocol: "HTTPS",
    message_type: "canonical-order",
    source: "x12-translator",
    target: "integration-api",
    owners: ["b2b-operations", "erp-integration"],
    downstream_systems: ["integration-api"],
    downstream_interfaces: ["if-integration-erp"],
    lifecycle: "production",
    version: "1.4",
    sla: "Route within 1 minute",
    last_status: "healthy",
    last_success_at: hoursAgo(1),
    business_impact: "Canonical orders never reach backend routing.",
  },
  {
    key: "if-integration-erp",
    name: "Integration API to McKesson ERP",
    description: "Integration API posts the order to McKesson ERP.",
    type: "REST",
    protocol: "HTTPS",
    message_type: "order-create",
    source: "integration-api",
    target: "mckesson-erp",
    owners: ["erp-integration"],
    downstream_systems: ["mckesson-erp"],
    downstream_interfaces: [
      "if-erp-inventory",
      "if-erp-orderstatus",
      "if-erp-notifications",
    ],
    lifecycle: "production",
    version: "1.4",
    sla: "ERP ack within 3 minutes",
    last_status: "healthy",
    last_success_at: hoursAgo(1),
    business_impact: "Orders are not created in the ERP of record.",
  },
  {
    key: "if-erp-inventory",
    name: "ERP to Inventory Service",
    description: "ERP updates inventory reservations for the order.",
    type: "EVENT",
    protocol: "Kafka",
    message_type: "inventory-updated",
    source: "mckesson-erp",
    target: "inventory-service",
    owners: ["erp-integration"],
    downstream_systems: ["inventory-service"],
    downstream_interfaces: [],
    lifecycle: "production",
    version: "3.0",
    sla: "Reflect within 5 minutes",
    last_status: "healthy",
    last_success_at: hoursAgo(1),
    business_impact: "Stock levels become inaccurate.",
  },
  {
    key: "if-erp-orderstatus",
    name: "ERP to Order Status API",
    description: "ERP publishes order status changes to the Order Status API.",
    type: "REST",
    protocol: "HTTPS",
    message_type: "order-status",
    source: "mckesson-erp",
    target: "order-status-api",
    owners: ["erp-integration"],
    downstream_systems: ["order-status-api"],
    downstream_interfaces: [],
    lifecycle: "production",
    version: "3.0",
    sla: "Reflect within 5 minutes",
    last_status: "healthy",
    last_success_at: hoursAgo(1),
    business_impact: "Partners cannot see order progress.",
  },
  {
    key: "if-erp-notifications",
    name: "ERP to Customer Notifications",
    description: "ERP triggers customer confirmations and exception alerts.",
    type: "EVENT",
    protocol: "Kafka",
    message_type: "notification",
    source: "mckesson-erp",
    target: "customer-notifications",
    owners: ["erp-integration"],
    downstream_systems: ["customer-notifications"],
    downstream_interfaces: [],
    lifecycle: "production",
    version: "3.0",
    sla: "Send within 10 minutes",
    last_status: "healthy",
    last_success_at: hoursAgo(1),
    business_impact: "Customers miss order confirmations and alerts.",
  },
  {
    key: "if-erp-855",
    name: "Order Acknowledgment 855",
    description: "Outbound EDI 855 purchase order acknowledgment back to the hospital.",
    type: "EDI",
    protocol: "X12",
    message_type: "855",
    source: "mckesson-erp",
    target: "hospital-123",
    middleware: ["integration-api", "x12-translator", "edi-gateway"],
    data_entities: ["order-ack"],
    owners: ["b2b-operations"],
    downstream_systems: ["hospital-123"],
    downstream_interfaces: [],
    lifecycle: "production",
    version: "2.1",
    sla: "Acknowledge within 15 minutes",
    last_status: "healthy",
    last_success_at: hoursAgo(2),
    business_impact: "Hospital cannot confirm the order was accepted.",
  },
  {
    key: "if-hospital-fhir",
    name: "Patient FHIR API",
    description: "REST/FHIR patient demographics feed used to enrich orders.",
    type: "FHIR",
    protocol: "HL7-FHIR",
    message_type: "Patient",
    source: "hospital-123",
    target: "integration-api",
    owners: ["hospital-systems", "erp-integration"],
    downstream_systems: ["integration-api"],
    downstream_interfaces: [],
    lifecycle: "production",
    version: "R4",
    sla: "Respond within 2 seconds",
    last_status: "healthy",
    last_success_at: hoursAgo(1),
    business_impact: "Order enrichment lacks current patient context.",
  },
  {
    key: "if-inventory-supplier",
    name: "Supplier Replenishment 850",
    description: "Automated outbound EDI 850 reorder to suppliers when stock is low.",
    type: "EDI",
    protocol: "X12",
    message_type: "850",
    source: "inventory-service",
    target: "supplier-edi",
    middleware: ["x12-translator", "edi-gateway"],
    data_entities: ["purchase-order"],
    owners: ["b2b-operations"],
    downstream_systems: ["supplier-edi"],
    downstream_interfaces: [],
    lifecycle: "development",
    version: "0.9",
    sla: "Send within 30 minutes",
    last_status: "healthy",
    last_success_at: hoursAgo(6),
    business_impact: "Automatic supplier replenishment does not fire.",
  },
];
