const now = new Date();
const daysAgo = (d) => new Date(now.getTime() - d * 24 * 3600 * 1000);

export const operationalKnowledge = [
  {
    key: "knowledge-erp-timeout-runbook",
    type: "runbook",
    title: "Apex ERP order-create timeout triage",
    interface_key: "if-integration-erp",
    business_process_key: "hospital-order-fulfillment",
    source_system: "runbook-catalog",
    tags: ["erp", "timeout", "order-create", "rest"],
    observed_at: daysAgo(12),
    text: "When order-create calls to Apex ERP time out, first verify ERP health, connection pool saturation, and database response time before restarting upstream senders. Confirm whether downstream inventory and order status updates are delayed.",
  },
  {
    key: "knowledge-erp-timeout-incident",
    type: "incident_note",
    title: "Prior ERP timeout affected order acknowledgments",
    interface_key: "if-integration-erp",
    business_process_key: "hospital-order-fulfillment",
    source_system: "incident-history",
    tags: ["erp", "acknowledgment", "855", "latency"],
    observed_at: daysAgo(21),
    text: "A previous p95 timeout spike on Integration API to Apex ERP delayed EDI 855 acknowledgments and partner notifications. The confirmed fault domain was Apex ERP saturation, not the EDI Gateway.",
  },
  {
    key: "knowledge-x12-backlog-runbook",
    type: "runbook",
    title: "X12 translation queue backlog response",
    interface_key: "if-gateway-x12",
    business_process_key: "hospital-order-fulfillment",
    source_system: "runbook-catalog",
    tags: ["x12", "translation", "gateway", "850"],
    observed_at: daysAgo(9),
    text: "For inbound 850 translation backlog, check EDI Gateway queue depth, X12 Translator worker health, and recent malformed partner envelopes. Do not restart Apex ERP until translation latency is ruled out.",
  },
  {
    key: "knowledge-partner-notification-incident",
    type: "incident_note",
    title: "Partner notification publisher failure pattern",
    interface_key: "if-erp-notifications",
    business_process_key: "hospital-order-fulfillment",
    source_system: "incident-history",
    tags: ["notification", "kafka", "partner", "confirmation"],
    observed_at: daysAgo(32),
    text: "Partner confirmation event failures usually localize to the Partner Notifications service or Kafka publish path after Apex ERP has already accepted the order. Validate ERP order creation before paging B2B gateway owners.",
  },
  {
    key: "knowledge-supplier-ack-timeout-runbook",
    type: "runbook",
    title: "Supplier EDI acknowledgment timeout triage",
    interface_key: "if-inventory-supplier",
    business_process_key: "supplier-replenishment",
    source_system: "runbook-catalog",
    tags: ["supplier", "edi", "850", "acknowledgment"],
    observed_at: daysAgo(6),
    text: "For missing supplier acknowledgments, check outbound 850 transmission logs, Supplier EDI endpoint availability, and EDI Gateway retry counts. Confirm whether inventory reorder triggers are still being generated.",
  },
  {
    key: "knowledge-supplier-replenishment-incident",
    type: "incident_note",
    title: "Supplier replenishment delayed by gateway retry storm",
    interface_key: "if-inventory-supplier",
    business_process_key: "supplier-replenishment",
    source_system: "incident-history",
    tags: ["supplier", "replenishment", "retry", "gateway"],
    observed_at: daysAgo(18),
    text: "A gateway retry storm previously delayed supplier replenishment EDI orders even though Inventory Service continued creating reorder events. The fastest confirmation was comparing Inventory Service trigger timestamps with EDI Gateway outbound acknowledgments.",
  },
  {
    key: "knowledge-inventory-impact-note",
    type: "business_context",
    title: "Inventory update impact on supplier replenishment",
    interface_key: "if-erp-inventory",
    business_process_key: "supplier-replenishment",
    source_system: "process-inventory",
    tags: ["inventory", "replenishment", "stock", "erp"],
    observed_at: daysAgo(15),
    text: "Supplier Replenishment depends on timely ERP inventory update events. If inventory-updated messages lag, low-stock reorder automation can miss the 30-minute supplier transmission SLA.",
  },
  {
    key: "knowledge-order-flow-context",
    type: "business_context",
    title: "Hospital order fulfillment dependency summary",
    interface_key: "if-hospital-850",
    business_process_key: "hospital-order-fulfillment",
    source_system: "process-inventory",
    tags: ["hospital", "order", "850", "fulfillment"],
    observed_at: daysAgo(4),
    text: "Hospital Order Fulfillment begins with inbound EDI 850 purchase orders, passes through gateway and X12 translation, then relies on Apex ERP to create orders and publish inventory, status, and notification updates.",
  },
];